package io.github.diskria.lapis.ksp.phases.generator

import io.github.diskria.lapis.ksp.Lapis

object GeneratorConstants {
    const val GENERATED_HEADER: String = "Auto-generated by ${Lapis.NAME}. Do not edit!"
    val INDENT: String = " ".repeat(4)
}
