[versions]
projektor = "6.+"

ksp = "2.3.6"

mixin = "0.8.7"
mixin-extras = "0.5.3"

asm = "9.9.1"

lapis-annotations = "0.9.1"

poetesse = "0.1.0"
kotlin-poet-ksp = "2.3.0"

kotlin-serialization-json = "1.11.0"

auto-service = "1.2.0"
auto-service-annotations = "1.1.1"

[plugins]
projektor = { id = "io.github.diskria.projektor", version.ref = "projektor" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixin-extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixin-extras" }

asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }

lapis-annotations = { group = "io.github.recrafter", name = "lapis-annotations", version.ref = "lapis-annotations" }

poetesse = { group = "io.github.diskria", name = "poetesse", version.ref = "poetesse" }
kotlin-poet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlin-poet-ksp" }

kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlin-serialization-json" }

auto-service = { group = "dev.zacsweers.autoservice", name = "auto-service-ksp", version.ref = "auto-service" }
auto-service-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "auto-service-annotations" }
