[versions]
auto-service = "1.2.0"
auto-service-annotations = "1.1.1"
ksp = "2.3.11"
mixin = "0.8.7"
mixin-extras = "0.5.5"
asm = "9.9.1"
poetesse = "0.1.4"
kotlin-poet-ksp = "2.4.0"
kotlin-serialization-json = "1.11.0"

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
auto-service-ksp = { group = "dev.zacsweers.autoservice", name = "auto-service-ksp", version.ref = "auto-service" }
auto-service-annotations = { group = "com.google.auto.service", name = "auto-service-annotations", version.ref = "auto-service-annotations" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixin-extras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixin-extras" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
poetesse = { group = "io.github.diskria", name = "poetesse", version.ref = "poetesse" }
kotlin-poet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlin-poet-ksp" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json-jvm", version.ref = "kotlin-serialization-json" }

ksp-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
