package io.github.diskria.lapis.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import io.github.diskria.lapis.ksp.logging.KspArguments
import io.github.diskria.lapis.ksp.logging.Logger
import io.github.diskria.lapis.ksp.phases.ProcessingPhase
import io.github.diskria.lapis.ksp.phases.generator.Generator
import io.github.diskria.lapis.ksp.phases.lowering.Lowering
import io.github.diskria.lapis.ksp.phases.lowering.models.IrPatch
import io.github.diskria.lapis.ksp.phases.parser.SymbolParser
import io.github.diskria.lapis.ksp.phases.validator.FrontendValidator
import io.github.diskria.poetesse.Poetesse
import java.util.*

class LapisSymbolProcessor(
    private val kspArguments: KspArguments,
    private val codeGenerator: CodeGenerator,
    private val logger: Logger,
) : SymbolProcessor {

    private val lowering: Lowering = Lowering(kspArguments, logger)
    private val patches: SortedMap<String, IrPatch> = sortedMapOf()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val parser = SymbolParser(resolver, logger)
        logger.setPhase(ProcessingPhase.PARSING)
        val parserResult = parser.parse()

        logger.setPhase(ProcessingPhase.VALIDATION)
        val validatorResult = FrontendValidator(logger).validate(parserResult)

        logger.setPhase(ProcessingPhase.TRANSFORMATION)
        val irResult = lowering.lower(validatorResult)
        irResult.patches.forEach { patches[it.className.qualifiedName] = it }

        return emptyList()
    }

    override fun finish() {
        generate()
    }

    override fun onError() {
        generate()
    }

    private fun generate() {
        logger.setPhase(ProcessingPhase.GENERATION)
        Generator(kspArguments, codeGenerator, logger).generate(patches.values.toList())
    }
}

val kspPoetesse = Poetesse {
    commentHeader = "Auto-generated by Lapis KSP. Do not edit!"
}

inline fun <T> kspPoetesse(block: Poetesse.() -> T): T =
    kspPoetesse.block()
