package io.github.diskria.lapis.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import io.github.diskria.lapis.ksp.phases.generator.Generator
import io.github.diskria.lapis.ksp.phases.lowering.Lowering
import io.github.diskria.lapis.ksp.phases.lowering.models.IrPatch
import io.github.diskria.lapis.ksp.phases.parser.SymbolParser
import io.github.diskria.lapis.ksp.phases.validator.FrontendValidator
import io.github.diskria.poetesse.Poetesse
import io.github.diskria.poetesse.java.JPAnnotation
import io.github.diskria.poetesse.java.JPClassName
import io.github.diskria.poetesse.java.JPTypeName
import java.util.*

class LapisSymbolProcessor(
    private val options: KspOptions,
    private val codeGenerator: CodeGenerator,
    private val logger: KspLogger,
) : SymbolProcessor {

    private val poetesse = Poetesse {
        commentHeader = "Auto-generated by Lapis KSP. Do not edit!"
        javaNullabilityResolver = KspJavaNullabilityResolver(
            nullableAnnotationClassName = options.nullableAnnotation?.let { JPClassName.bestGuess(it) },
            nonNullAnnotationClassName = options.nonNullAnnotation?.let { JPClassName.bestGuess(it) },
        )
    }

    private val lowering: Lowering by lazy { Lowering(options, poetesse, logger) }
    private val patches: SortedMap<String, IrPatch> = sortedMapOf()

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val parser = SymbolParser(resolver, logger)
        logger.setPhase(KspLogger.Phase.PARSING)
        val parsedPatches = parser.parse()

        logger.setPhase(KspLogger.Phase.VALIDATION)
        val validatedPatches = FrontendValidator(resolver.builtIns, logger).validate(parsedPatches)

        logger.setPhase(KspLogger.Phase.TRANSFORMATION)
        val irPatches = lowering.lower(validatedPatches)
        irPatches.forEach { patches[it.className.qualifiedName] = it }

        return emptyList()
    }

    override fun finish() {
        generate()
    }

    override fun onError() {
        generate()
    }

    private fun generate() {
        logger.setPhase(KspLogger.Phase.GENERATION)
        Generator(options, poetesse, codeGenerator, logger).generate(patches.values.toList())
    }
}

private class KspJavaNullabilityResolver(
    private val nullableAnnotationClassName: JPClassName?,
    private val nonNullAnnotationClassName: JPClassName?,
) : Poetesse.JavaNullabilityResolver {

    override fun isNullable(typeName: JPTypeName): Boolean =
        nullableAnnotationClassName != null && typeName.annotations().any { it.type() == nullableAnnotationClassName }

    override fun setNullable(typeName: JPTypeName, nullable: Boolean): JPTypeName {
        if (nullableAnnotationClassName == null && nonNullAnnotationClassName == null) return typeName
        val targetAnnotation = if (nullable) nullableAnnotationClassName else nonNullAnnotationClassName
        val cleanAnnotations = typeName.annotations().filterNot {
            it.type() == nullableAnnotationClassName || it.type() == nonNullAnnotationClassName
        }
        val finalAnnotations = if (targetAnnotation != null) {
            cleanAnnotations + JPAnnotation.builder(targetAnnotation).build()
        } else {
            cleanAnnotations
        }
        return typeName.withoutAnnotations().annotated(finalAnnotations)
    }
}
